apiVersion: apps/v1
kind: Deployment
metadata:
  name: i27-eureka-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      name: i27-eureka-dev
  template:
    metadata:
      labels:
        name: i27-eureka-dev
    spec:
      containers:
        - name: i27-eureka-dev
          image: DIT
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: i27-eureka-dev
spec:
  selector:
    name: i27-eureka-dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8761
  type: NodePort
